sonar.organization=alexdaniel593
sonar.projectKey=AlexDaniel593_Master-Gateway

sonar.sources=backend/src
sonar.tests=backend/test
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/main.ts

sonar.sourceEncoding=UTF-8
sonar.verbose=false
